sources:
  - name: jaffle_shop
    description: Source data comes from Jaffle Shop
    schema: jaffle_shop
    database: raw
    tables:
      - name: customers
        description: customers dataset where one row represents one customer
        columns:
          - name: id
            data_tests:
              - not_null
              - unique
          - name: last_name
            description: "{{ doc('last_name')}}"


      - name: orders
        description: orders dataset where one row represents one orders
        config:   
          freshness:
            warn_after:
              count: 12
              period: hour
            error_after:
              count: 24
              period: hour
          loaded_at_field: _etl_loaded_at
        columns:
          - name: id
            data_tests:
              - not_null
              - unique
          - name: user_id
            data_tests:
              - not_null
              - relationships:
                  arguments: 
                    to: source('jaffle_shop','customers')
                    field: id
          - name: status
            data_tests:
              - accepted_values:
                  arguments: 
                    values: ['placed', 'return_pending','returned','completed','shipped']